version: '2.1'

services:
  aws-test:
    build: docker
    command: ./bin/launcher ./bin/run-tests
    env_file:
      - docker/ec2.env
      - docker/secrets.env
    volumes:
      - ./docker/bin:/usr/src/app/bin
      - ./docker/keys:/usr/src/app/keys
      - ./results:/usr/src/app/results

  dtests:
    build: .
    volumes:
      - .:/usr/src/cstar/cassandra-dtest
      - .m2:/root/.m2
      - ./results:/usr/src/cstar/results

  unittests:
    build: .
    environment:
      - ONLY_UNIT_TESTS=true
    volumes:
      - .:/usr/src/cstar/cassandra-dtest
      - .m2:/root/.m2
      - ./results:/usr/src/cstar/results
